### ISSUE TITLE
Nicknames in upper case not working

### ISSUE THREAD

**Issue by kazyavich** [DogLoverPink/EssentialsX-Target-Selectors#10]
Nicknames in upper case not working (ex. SABUKA1234)
 
EssentialsX-Target-Selectors 1.7.1 (Purpur 1.19.2)
 
Error: Player not found.

**Comment by DogLoverPink** [comment]
I don't quite understand what the issue you are describing is. Can you provide the full command that you tried to execute?

**Comment by IdelTeam** [comment]
/tp @p
Error: Player not found

**Comment by DogLoverPink** [comment]
Hmm, so I have tested your provided command, and it has a very interesting result 
![image](https://user-images.githubusercontent.com/64995932/213804679-40e69ddb-928f-4c2c-ae50-1cd432b049cb.png)
Despite saying "Player not found", it also did teleport me, is this the same situation for you? 

Another question, is this affecting any other commands?

**Comment by IdelTeam** [comment]
Yes, this is the same situation. This isn't affecting any other commands.
