### ISSUE TITLE
Can't set number of items

### ISSUE THREAD

**Issue by Skyw0lf07** [DogLoverPink/EssentialsX-Target-Selectors#11]
When I execute /give @r wooden_sword 1 it doesn't work as shown below. If I don't set a number of items, it works. If I set my name (instead of using the plugin) it works
 
![image](https://github.com/DogLoverPink/EssentialsX-Target-Selectors/assets/81262586/4895bd0f-8a78-4fa9-8ac4-c7baacda0ef1)

**Steps for recreation:**
 1. Execute the command
 2. Not receiving the item
 
There aren't errors in the console:
![image](https://github.com/DogLoverPink/EssentialsX-Target-Selectors/assets/81262586/9304ffa7-7f7d-4847-b165-3637450c7488)

 
I'm using the version 1.7.1 and paper 1.16.5

**Comment by DogLoverPink** [comment]
Wow, I'm surprised this has not been reported yet. I'll try my best to fix this quickly.

Thank you for the report!

**Comment by DogLoverPink** [comment]
Fixed in release [1.7.2](https://github.com/DogLoverPink/EssentialsX-Target-Selectors/releases/tag/v1.7.2)
