### ISSUE TITLE
[BUG ]sudo @p warp spawn not working

### ISSUE THREAD

**Issue by antiGriefer** [DogLoverPink/EssentialsX-Target-Selectors#4]
Heyy great plugin, but when I put this in a command block:''sudo @p warp spawn'' it doesnt work. It will give the error: Player not found.
but "sudo @p spawn" works fine. Would be great if u can fix this.

Minecraft version: 1.19
Plugin version: Latest

**Comment by DogLoverPink** [comment]
Hey! I will make sure to check htis out and release a fix soon! Thanks for reporting :)

**Comment by DogLoverPink** [comment]
Hey @antiGriefer, I couldn't mananage to reproduce this issue, if you are having trouble with sudo, you can simply do "warp spawn @p" in the command block.

**Comment by antiGriefer** [comment]
Hey @DogLoverPink , I tried it again and still can't do either of these commands. No idea what could be the cause

**Comment by DogLoverPink** [comment]
Hmm, then this is quite strange, I don't really know what to do. Do you have any ideas?

**Comment by Thomas-Lecuppre** [comment]
Maybe it's due to the fact that you use a plugin as "Sudo Command" to execute Essential command (because it was not working without @DogLoverPink plugin).

Try to remove Sudo Command and just normally use Essential command with this plugin.

**Comment by DogLoverPink** [comment]
@Thomas-Lecuppre is correct, the selectors will only work on commands from Essentials itself, if you have another plugin that also has a sudo command, you could instead do /esudo to avoid confliction.
